name: 'pmpm'
version: '1.0.0'
config-version: 2

profile: 'firsthand'

vars:
    source_name: tuva_core                  # configuration required
                                       # name describing the dataset feeding
                                       # this project - typically matches input
                                       # schema name

    input_database: transformed_data               # configuration required
                                       # name of the database where sources
                                       # feeding this project are stored
    
    input_schema: tuva_core                 # configuration required
                                       # name of the schema where sources
                                       # feeding this project are stored

    pharmacy_schema: tuva_claims_input                 # configuration required
                                       # name of the schema where sources
                                       # feeding this project are stored

    output_database: transformed_data              # configuration required
                                       # name of the database where output of
                                       # this project should be written

    output_schema: tuva_pmpm        # configuration required
                                       # name of the schema where output of this
                                       # schema should be written

    encounter: "{{ source(var('source_name'),'encounter') }}"
    coverage: "{{ source(var('source_name'),'coverage') }}"
    pharmacy_claim: "{{ source(var('source_name'),'pharmacy_claim') }}"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
